version: '3.9'

services:
   frontend:
    image: root938/tomato-food-app-frontend:1.0
    container_name: frontend
    ports:
     - "3000:80"
    networks:
      - shop
   admin:
     image: root938/tomato-food-app-admin:1.0
     container_name: admin
     ports:
      - "3001:80"
     networks:
       - shop
   backend:
     image: root938/tomato-food-app-backend:1.0
     container_name: backend
     ports:
      - "4000:4000"
     networks:
       - shop
     restart: always
     environment:
       - MONGO_URI:mongodb://mongodb:27017/store
      
   mongodb:
     image: mongo:4.4
     container_name: mongodb
     ports:
      - "27017:27017"
     environment:
      - MONGO_INITDB_DATABASE=store
     volumes:
      - mongo-db:/data/db
     networks:
      - shop 
   prometheus:
     image: prom/prometheus:latest
     container_name: prometheus
     ports:
      - "9090:9090"
     volumes:
       - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
     networks:
      - shop
     restart: always
     depends_on:
       - backend
       - mongodb
   grafana:
     image: grafana/grafana:latest
     container_name: grafana
     ports:
      - "3002:3000"
     environment:
       - GF_SECURITY_ADMIN_USER=admin
       - GF_SECURITY_ADMIN_PASSWORD=admin
     networks:
      - shop
     restart: always
     depends_on:
      - prometheus
      
volumes:
    mongo-db:
networks:
   shop:
