version: '3.9'

services:
   frontend:
    image: root938/tomato-food-app-frontend:1.0
    ports:
     - "3000:80"
    networks:
      - shop
   admin:
     image: root938/tomato-food-app-admin:1.0
     ports:
      - "3001:80"
     networks:
       - shop
   backend:
     image: root938/tomato-food-app-backend:1.0
     ports:
      - "4000:4000"
     networks:
       - shop
     restart: always
     environment:
       - MONGO_URI:mongodb://mongodb:27017/store
      
   mongodb:
     image: mongo:4.4
     container_name: mongodb
     ports:
      - "27017:27017"
     environment:
      - MONGO_INITDB_DATABASE=store
     volumes:
      - mongo-db:/data/db
     networks:
      - shop 


volumes:
    mongo-db:
networks:
   shop:
