global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323']

  - job_name: 'backend'
    static_configs:
      - targets: ['backend:4000']

  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb:27017']
